version: '2'
services:
    microservices-app:
        image: microservices
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://microservices-mysql:3306/microservices?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://microservices-elasticsearch:9200
    microservices-mysql:
        extends:
            file: mysql.yml
            service: microservices-mysql
    microservices-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: microservices-elasticsearch
